Onboarding fixes
psychic-api/psychic pull request #45
Opened 2023-06-14 14:31 UTC by jasonwcfan

- Update some styling (mainly dark mode)
- moved some sidebar items around
- renamed playground to create-connection everywhere

2023-06-17 22:08 UTC, Ayan-Bandyopadhyay requested changes

2023-06-17 22:08 UTC, Ayan-Bandyopadhyay commented on dashboard/src/pages/syncs.tsx
> +      <div className="block items-center justify-between border-b border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800 sm:flex">
regression here, this is gonna bring back the dark mode w/ white background issue

2023-06-19 14:19 UTC, jasonwcfan commented on dashboard/src/pages/syncs.tsx
> +      <div className="block items-center justify-between border-b border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800 sm:flex">
it doesn't cuz of the dark:bg-gray className. The bg-white is to keep it consistent with other pages that have a white background while the flowbite default is a light grey

2023-06-19 16:17 UTC, Ayan-Bandyopadhyay approved these changes

2023-06-19 16:17 UTC, merged